---

- name: Configuracion repositorio Crio 1
  command: wget -O /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
  become: yes  
 
- name: Configuracion repositorio Crio 2
  command: wget -O /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo 
  become: yes  
  
- name: Execute cat 
  shell:
    cmd: |
      cat <<EOF > /etc/modules-load.d/crio.conf
      overlay
      br_netfilter
      EOF
  become: yes

- name: Instalar Crio
  command: dnf install crio -y
  become: yes    

- name: Activar Crio
  command: systemctl enable crio
  become: yes    
  
- name: Iniciar Crio
  command: systemctl start crio
  become: yes      
  
- name: Configurar repositorio de kubernetes
  shell:
    cmd: |
      cat <<EOF > /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
      EOF
  become: yes
  
- name: Instalar Kubernetes Paso 1
  command: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  become: yes
  
- name: Instalar Kubernetes Paso 2
  command: systemctl enable kubelet
  become: yes 

- name: Instalar Kubernetes Paso 3
  command: systemctl start kubelet
  become: yes  

- name: Instalar Kubernetes Paso 4
  command: dnf --showduplicates list available kubelet --disableexcludes=kubernetes > /tmp/VersionesKubernetes.txtss
  become: yes 

- name: Instalar Kubernetes Paso 5
  command: dnf install kubelet-1.21.9-0 kubeadm-1.21.9-0 kubectl-1.21.9-0 --disableexcludes=kubernetes -y
  become: yes