---

rpms: ['nfs-utils', 'net-tools']

services: ['nfs-server']

ips_nfs: ['/srv/nfs	10.0.1.10(rw,sync)', '/srv/nfs	10.0.1.11(rw,sync)', '/srv/nfs	10.0.1.12(rw,sync)']

firewallservices:  ['nfs', 'rpc-bind', 'mountd']

ip_nfs: '10.0.1.13'