---

- name: Configuramos el firewall SDN Azure
  firewalld:
    port: "{{ item }}"
    permanent: yes
    zone: public
    state: enabled
  become: yes
  with_items:
    - 10250/tcp
    - 30000-32767/tcp

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

